version: '3.4'

services:
  calculate.api:
    container_name: calculateapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  cars.api:
    container_name: carsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - calculate.api
        - cars.api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
    - "7000:80"
   
